EXPERIMENT:
  NAME: ""
  TAG: "kd,eegnetv4,eegnetv1"
  PROJECT: "BCIIV2a_baselines"
DATASET:
  TYPE: "BCIIV2a"
  CHANNELS: 22
  POINTS: 1125
  NUM_CLASSES: 4
DISTILLER:
  TYPE: "KD"
  TEACHER: "BCIIV2a_eegnetv4"
  STUDENT: "BCIIV2a_eegnetv1"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 200
  LR: 0.003
