EXPERIMENT:
  NAME: ""
  TAG: "gkd,hgrn,sdt"
  PROJECT: "DecMeg2014_baselines"
DATASET:
  TYPE: "DecMeg2014"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
DISTILLER:
  TYPE: "GKD"
  TEACHER: "DecMeg2014_hgrn"
  STUDENT: "sdt"
SOLVER:
  BATCH_SIZE: 1024
  EPOCHS: 100
  LR: 0.003

