EXPERIMENT:
  NAME: ""
  TAG: "vanilla,hgrn"
  PROJECT: "DecMeg2014_baselines"
DATASET:
  TYPE: "DecMeg2014"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
DISTILLER:
  TYPE: "NONE"
  TEACHER: ""
  STUDENT: "DecMeg2014_hgrn"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 100
  LR: 0.003

