EXPERIMENT:
  NAME: ""
  TAG: "vanilla,lfcnn"
  PROJECT: "DecMeg2014_baselines"
DATASET:
  TYPE: "DecMeg2014"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
DISTILLER:
  TYPE: "NONE"
  TEACHER: ""
  STUDENT: "DecMeg2014_lfcnn"
SOLVER:
  BATCH_SIZE: 32
  EPOCHS: 100
  LR: 0.0003
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

