EXPERIMENT:
  NAME: ""
  TAG: "vanilla,sdt"
  PROJECT: "DecMeg2014_baselines"
DATASET:
  TYPE: "DecMeg2014"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
DISTILLER:
  TYPE: "NONE"
  TEACHER: ""
  STUDENT: "sdt"
SOLVER:
  BATCH_SIZE: 512
  EPOCHS: 100
  LR: 0.003

