EXPERIMENT:
  NAME: ""
  TAG: "shapleyfakd-ce,varcnn,sdt"
  PROJECT: "DecMeg2014_baselines"
DATASET:
  TYPE: "DecMeg2014"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
DISTILLER:
  TYPE: "ShapleyFAKD"
  TEACHER: "DecMeg2014_varcnn"
  STUDENT: "sdt"
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 20
  LR: 0.003
ShapleyFAKD:
  LOSS:
    CE_WEIGHT: 0.0
    FA_WEIGHT: 1000