EXPERIMENT:
  NAME: ""
  TAG: "vanilla,eegnetv4"
  PROJECT: "BCIIV2a_baselines"
DATASET:
  TYPE: "BCIIV2a"
  CHANNELS: 22
  POINTS: 1125
  NUM_CLASSES: 4
DISTILLER:
  TYPE: "NONE"
  TEACHER: ""
  STUDENT: "BCIIV2a_eegnetv4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 200
  LR: 0.003
