EXPERIMENT:
  NAME: ""
  TAG: "vanilla,lfcnn"
  PROJECT: "BCIIV2a_baselines"
DATASET:
  TYPE: "BCIIV2a"
  CHANNELS: 22
  POINTS: 1125
  NUM_CLASSES: 4
DISTILLER:
  TYPE: "NONE"
  TEACHER: ""
  STUDENT: "BCIIV2a_lfcnn"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 100
  LR: 0.0003
