EXPERIMENT:
  NAME: ""
  TAG: "vanilla,sdt"
  PROJECT: "BCIIV2a_baselines"
DATASET:
  TYPE: "BCIIV2a"
  CHANNELS: 22
  POINTS: 1125
  NUM_CLASSES: 4
DISTILLER:
  TYPE: "NONE"
  TEACHER: ""
  STUDENT: "sdt"
SOLVER:
  BATCH_SIZE: 64 # 256,512,1024
  EPOCHS: 100
  LR: 0.0003
