EXPERIMENT:
  NAME: ""
  TAG: "scfakd,lfcnn,sdt"
  PROJECT: "CamCAN_baselines"
DATASET:
  TYPE: "CamCAN"
  CHANNELS: 204
  POINTS: 100
  NUM_CLASSES: 2
DISTILLER:
  TYPE: "SCFAKD"
  TEACHER: "CamCAN_lfcnn"
  STUDENT: "sdt"
SOLVER:
  BATCH_SIZE: 512
  EPOCHS: 100
  LR: 0.003
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
