EXPERIMENT:
  NAME: ""
  TAG: "scfakd,hgrn,sdt"
  PROJECT: "DecMeg2014_baselines"
DATASET:
  TYPE: "DecMeg2014"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
DISTILLER:
  TYPE: "SCFAKD"
  TEACHER: "DecMeg2014_hgrn"
  STUDENT: "sdt"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 20
  LR: 0.003
