EXPERIMENT:
  NAME: ""
  TAG: "shapleyfakd,lfcnn,sdt"
  PROJECT: "DecMeg2014_baselines"
  REPETITION_NUM: 3
DATASET:
  TYPE: "DecMeg2014"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
DISTILLER:
  TYPE: "ShapleyFAKD"
  TEACHER: "DecMeg2014_lfcnn"
  STUDENT: "sdt"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 30
  LR: 0.003
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
