EXPERIMENT:
  NAME: ""
  TAG: "shapleyfakd+kd,hgrn,sdt"
  PROJECT: "DecMeg2014_baselines"
DATASET:
  TYPE: "DecMeg2014"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
DISTILLER:
  TYPE: "ShapleyFAKD"
  TEACHER: "DecMeg2014_hgrn"
  STUDENT: "sdt"
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 20
  LR: 0.003
ShapleyFAKD:
  WITH_KD: True
  TEMPERATURE: 4
  LOSS:
    CE_WEIGHT: 0.1
    KD_WEIGHT: 0.9
    FA_WEIGHT: 1000
