EXPERIMENT:
  NAME: ""
  TAG: "fakd,lfcnn,std"
  PROJECT: "CamCAN_baselines"
DATASET:
  TYPE: "CamCAN"
  CHANNELS: 204
  POINTS: 100
  NUM_CLASSES: 2
DISTILLER:
  TYPE: "FAKD"
  TEACHER: "CamCAN_lfcnn"
  STUDENT: "std"
SOLVER:
  BATCH_SIZE: 1024
  EPOCHS: 100
  LR: 0.001
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
