EXPERIMENT:
  NAME: ""
  TAG: "vanilla,hgrn"
  PROJECT: "CamCAN_baselines"
DATASET:
  TYPE: "CamCAN"
  CHANNELS: 204
  POINTS: 100
  NUM_CLASSES: 2
DISTILLER:
  TYPE: "NONE"
  TEACHER: ""
  STUDENT: "CamCAN_hgrn"
SOLVER:
  BATCH_SIZE: 1024
  EPOCHS: 100
  LR: 0.003
