EXPERIMENT:
  NAME: ""
  TAG: "vanilla,sdt"
  PROJECT: "CamCAN_baselines"
DATASET:
  TYPE: "CamCAN"
  CHANNELS: 204
  POINTS: 100
  NUM_CLASSES: 2
DISTILLER:
  TYPE: "NONE"
  TEACHER: ""
  STUDENT: "sdt"
SOLVER:
  BATCH_SIZE: 1024 # 128,256,512,1024,2048
  EPOCHS: 100
  LR: 0.0003  # 0.003,0.0003
