EXPERIMENT:
  NAME: ""
  TAG: "vanilla,lfcnn,std"
  PROJECT: "CamCAN_baselines"
DISTILLER:
  TYPE: "NONE"
  TEACHER: "lfcnn"
  STUDENT: "std5"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 30
  LR: 0.03
  LR_DECAY_STAGES: [15, 25]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
