EXPERIMENT:
  NAME: ""
  TAG: "shapleyfakd,hgrn,hgrn"
  PROJECT: "CamCAN_baselines"
DATASET:
  TYPE: "CamCAN"
  CHANNELS: 204
  POINTS: 100
  NUM_CLASSES: 2
DISTILLER:
  TYPE: "ShapleyFAKD"
  TEACHER: "CamCAN_hgrn"
  STUDENT: "CamCAN_hgrn"
SOLVER:
  BATCH_SIZE: 512
  EPOCHS: 20
  LR: 0.003
