EXPERIMENT:
  NAME: ""
  TAG: "gkd,varcnn,sdt"
  PROJECT: "CamCAN_baselines"
DATASET:
  TYPE: "CamCAN"
  CHANNELS: 204
  POINTS: 100
  NUM_CLASSES: 2
DISTILLER:
  TYPE: "GKD"
  TEACHER: "CamCAN_varcnn"
  STUDENT: "sdt"
SOLVER:
  BATCH_SIZE: 1024
  EPOCHS: 100
  LR: 0.003

