EXPERIMENT:
  NAME: ""
  TAG: "dkd,lfcnn,sdt"
  PROJECT: "DecMeg2014_baselines"
DATASET:
  TYPE: "DecMeg2014"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
DISTILLER:
  TYPE: "DKD"
  TEACHER: "DecMeg2014_lfcnn"
  STUDENT: "sdt"
SOLVER:
  BATCH_SIZE: 1024
  EPOCHS: 100
  LR: 0.003

